

services:
  db:
    image: postgres:17
    #restart: always
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB:   ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  file_service:
    build:
      context: ./file_service
    restart: no #always
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./file_service/storage:/app/storage
      - "C:/Users/Марина/source/repos/Software Design big hw 2/common:/app/common"
      - ./.env:/app/.env:ro
    ports:
      - "8001:8001"

  analysis_service:
    build:
      context: ./analysis_service
    restart: "no"
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env:ro
      - ./common:/app/common
    depends_on:
      - db
      - file_service
    ports:
      - "8002:8002"

  gateway:
    build:
      context: ./gateway
    restart: "no"
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env:ro
      - ./common:/app/common
    depends_on:
      - file_service
      - analysis_service
    ports:
      - "8000:8000"
    command: >
      uvicorn app.main:app --host 0.0.0.0 --port 8000

volumes:
  db_data:
